<?php

namespace OLabs\AVirtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function getCourses()
    {
        $qb = $this->queryCourses();
        $courses = $qb->getQuery()->execute();
        return $courses;
    }

    public function queryCourses()
    {
        $qb = $this->createQueryBuilder('c')
            ->orderBy("c.updatedAt", "DESC");
        return $qb;
    }

}
